# Salary Predictor:
Data Source: https://www.kaggle.com/datasets/rkiattisak/salaly-prediction-for-beginer

In [1]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [2]:
df=pd.read_csv('data_salary.csv')
df

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
370,35.0,Female,Bachelor's,Senior Marketing Analyst,8.0,85000.0
371,43.0,Male,Master's,Director of Operations,19.0,170000.0
372,29.0,Female,Bachelor's,Junior Project Manager,2.0,40000.0
373,34.0,Male,Bachelor's,Senior Operations Coordinator,7.0,90000.0
374,44.0,Female,PhD,Senior Business Analyst,15.0,150000.0

# EDA

In [3]:
# to display the first 5 data's
df.head()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0

In [4]:
# to display about the total number of rows and columns in the dataset
df.shape

(375, 6)

In [5]:
# to get detail information about the datset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375 entries, 0 to 374
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  373 non-null    float64
 1   Gender               373 non-null    object
 2   Education Level      373 non-null    object
 3   Job Title            373 non-null    object
 4   Years of Experience  373 non-null    float64
 5   Salary               373 non-null    float64
dtypes: float64(3), object(3)
memory usage: 17.7+ KB

In [6]:
# to know about how may data's are null in the dataframe
df.isnull().sum()

Age                    2
Gender                 2
Education Level        2
Job Title              2
Years of Experience    2
Salary                 2
dtype: int64

In [7]:
df.describe()

              Age  Years of Experience         Salary
count  373.000000           373.000000     373.000000
mean    37.431635            10.030831  100577.345845
std      7.069073             6.557007   48240.013482
min     23.000000             0.000000     350.000000
25%     31.000000             4.000000   55000.000000
50%     36.000000             9.000000   95000.000000
75%     44.000000            15.000000  140000.000000
max     53.000000            25.000000  250000.000000

In [8]:
# to choose the columns which one will be our Feature and Target
df.columns

Index(['Age', 'Gender', 'Education Level', 'Job Title', 'Years of Experience',
       'Salary'],
      dtype='object')

In [9]:
# dropping all the null values from the dataset
df1 = df.dropna()
df1.isnull().sum()

Age                    0
Gender                 0
Education Level        0
Job Title              0
Years of Experience    0
Salary                 0
dtype: int64

In [10]:
df1['Age'].unique()

array([32., 28., 45., 36., 52., 29., 42., 31., 26., 38., 48., 35., 40.,
       27., 44., 33., 39., 25., 51., 34., 47., 30., 41., 37., 24., 43.,
       50., 46., 49., 23., 53.])

In [11]:
df1['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [12]:
df1['Education Level'].unique()

array(["Bachelor's", "Master's", 'PhD'], dtype=object)

In [13]:
df1['Job Title'].unique()

array(['Software Engineer', 'Data Analyst', 'Senior Manager',
       'Sales Associate', 'Director', 'Marketing Analyst',
       'Product Manager', 'Sales Manager', 'Marketing Coordinator',
       'Senior Scientist', 'Software Developer', 'HR Manager',
       'Financial Analyst', 'Project Manager', 'Customer Service Rep',
       'Operations Manager', 'Marketing Manager', 'Senior Engineer',
       'Data Entry Clerk', 'Sales Director', 'Business Analyst',
       'VP of Operations', 'IT Support', 'Recruiter', 'Financial Manager',
       'Social Media Specialist', 'Software Manager', 'Junior Developer',
       'Senior Consultant', 'Product Designer', 'CEO', 'Accountant',
       'Data Scientist', 'Marketing Specialist', 'Technical Writer',
       'HR Generalist', 'Project Engineer', 'Customer Success Rep',
       'Sales Executive', 'UX Designer', 'Operations Director',
       'Network Engineer', 'Administrative Assistant',
       'Strategy Consultant', 'Copywriter', 'Account Manager',
       'Director of Marketing', 'Help Desk Analyst',
       'Customer Service Manager', 'Business Intelligence Analyst',
       'Event Coordinator', 'VP of Finance', 'Graphic Designer',
       'UX Researcher', 'Social Media Manager', 'Director of Operations',
       'Senior Data Scientist', 'Junior Accountant',
       'Digital Marketing Manager', 'IT Manager',
       'Customer Service Representative', 'Business Development Manager',
       'Senior Financial Analyst', 'Web Developer', 'Research Director',
       'Technical Support Specialist', 'Creative Director',
       'Senior Software Engineer', 'Human Resources Director',
       'Content Marketing Manager', 'Technical Recruiter',
       'Sales Representative', 'Chief Technology Officer',
       'Junior Designer', 'Financial Advisor', 'Junior Account Manager',
       'Senior Project Manager', 'Principal Scientist',
       'Supply Chain Manager', 'Senior Marketing Manager',
       'Training Specialist', 'Research Scientist',
       'Junior Software Developer', 'Public Relations Manager',
       'Operations Analyst', 'Product Marketing Manager',
       'Senior HR Manager', 'Junior Web Developer',
       'Senior Project Coordinator', 'Chief Data Officer',
       'Digital Content Producer', 'IT Support Specialist',
       'Senior Marketing Analyst', 'Customer Success Manager',
       'Senior Graphic Designer', 'Software Project Manager',
       'Supply Chain Analyst', 'Senior Business Analyst',
       'Junior Marketing Analyst', 'Office Manager', 'Principal Engineer',
       'Junior HR Generalist', 'Senior Product Manager',
       'Junior Operations Analyst', 'Senior HR Generalist',
       'Sales Operations Manager', 'Senior Software Developer',
       'Junior Web Designer', 'Senior Training Specialist',
       'Senior Research Scientist', 'Junior Sales Representative',
       'Junior Marketing Manager', 'Junior Data Analyst',
       'Senior Product Marketing Manager', 'Junior Business Analyst',
       'Senior Sales Manager', 'Junior Marketing Specialist',
       'Junior Project Manager', 'Senior Accountant', 'Director of Sales',
       'Junior Recruiter', 'Senior Business Development Manager',
       'Senior Product Designer', 'Junior Customer Support Specialist',
       'Senior IT Support Specialist', 'Junior Financial Analyst',
       'Senior Operations Manager', 'Director of Human Resources',
       'Junior Software Engineer', 'Senior Sales Representative',
       'Director of Product Management', 'Junior Copywriter',
       'Senior Marketing Coordinator', 'Senior Human Resources Manager',
       'Junior Business Development Associate', 'Senior Account Manager',
       'Senior Researcher', 'Junior HR Coordinator',
       'Director of Finance', 'Junior Marketing Coordinator',
       'Junior Data Scientist', 'Senior Operations Analyst',
       'Senior Human Resources Coordinator', 'Senior UX Designer',
       'Junior Product Manager', 'Senior Marketing Specialist',
       'Senior IT Project Manager', 'Senior Quality Assurance Analyst',
       'Director of Sales and Marketing', 'Senior Account Executive',
       'Director of Business Development', 'Junior Social Media Manager',
       'Senior Human Resources Specialist', 'Senior Data Analyst',
       'Director of Human Capital', 'Junior Advertising Coordinator',
       'Junior UX Designer', 'Senior Marketing Director',
       'Senior IT Consultant', 'Senior Financial Advisor',
       'Junior Business Operations Analyst',
       'Junior Social Media Specialist',
       'Senior Product Development Manager', 'Junior Operations Manager',
       'Senior Software Architect', 'Junior Research Scientist',
       'Senior Financial Manager', 'Senior HR Specialist',
       'Senior Data Engineer', 'Junior Operations Coordinator',
       'Director of HR', 'Senior Operations Coordinator',
       'Junior Financial Advisor', 'Director of Engineering'],
      dtype=object)

In [14]:
df1.columns

Index(['Age', 'Gender', 'Education Level', 'Job Title', 'Years of Experience',
       'Salary'],
      dtype='object')

In [15]:
# Choosing only the features that is relevant for the prediction
# You can also keep 'Job Title' in the dataframe but i haven't kept it
df2= df1.drop( ['Age', 'Gender','Job Title'], axis=1)
df2.head(10)

  Education Level  Years of Experience    Salary
0      Bachelor's                  5.0   90000.0
1        Master's                  3.0   65000.0
2             PhD                 15.0  150000.0
3      Bachelor's                  7.0   60000.0
4        Master's                 20.0  200000.0
5      Bachelor's                  2.0   55000.0
6        Master's                 12.0  120000.0
7      Bachelor's                  4.0   80000.0
8      Bachelor's                  1.0   45000.0
9             PhD                 10.0  110000.0

In [16]:
# Converting the Categorial data into numbers

from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df2['Education Level'] = label_encoder.fit_transform(df2['Education Level'])
df2.head()

   Education Level  Years of Experience    Salary
0                0                  5.0   90000.0
1                1                  3.0   65000.0
2                2                 15.0  150000.0
3                0                  7.0   60000.0
4                1                 20.0  200000.0

In [17]:
# Splitting the data into x and y for training and testing purpose

x=df2[['Education Level', 'Years of Experience']]
x.shape

(373, 2)

In [18]:
x.head(5)

   Education Level  Years of Experience
0                0                  5.0
1                1                  3.0
2                2                 15.0
3                0                  7.0
4                1                 20.0

In [19]:
y=df2[['Salary']]
y.head(5)

     Salary
0   90000.0
1   65000.0
2  150000.0
3   60000.0
4  200000.0

In [20]:
# Splitting the above data into training and testing data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size= 0.2,random_state = 9598)

In [21]:
# to know about the shape of traing and testing data

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(298, 2)
(75, 2)
(298, 1)
(75, 1)

In [22]:
# As it is the Regrssion Problem lets try all the Regression Algorith to get the best accuracy
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [23]:
# To train and fit the model
model.fit(x_train,y_train)

LinearRegression()

In [24]:
# to predict the data
y_pred = model.predict(x_test)
y_pred

array([[130293.72312675],
       [183733.0198562 ],
       [ 69249.9165435 ],
       [ 45499.11799708],
       [116751.51363635],
       [ 94667.52530712],
       [137898.23298055],
       [ 57374.51727029],
       [142169.12239996],
       [ 57374.51727029],
       [ 51436.81763369],
       [ 75187.61618011],
       [100605.22494372],
       [ 93000.71508993],
       [126022.83370734],
       [191337.52971   ],
       [ 63312.2169069 ],
       [ 45499.11799708],
       [159982.22130978],
       [ 33623.71872387],
       [ 45499.11799708],
       [ 76854.4263973 ],
       [ 45499.11799708],
       [ 81125.31581672],
       [149773.63225376],
       [ 93000.71508993],
       [149773.63225376],
       [ 63312.2169069 ],
       [ 93000.71508993],
       [ 82792.12603391],
       [ 63312.2169069 ],
       [ 88729.82567051],
       [ 57374.51727029],
       [ 39561.41836048],
       [ 51436.81763369],
       [ 51436.81763369],
       [155711.33189036],
       [ 75187.61618011],
       [ 81125.31581672],
       [ 81125.31581672],
       [ 75187.61618011],
       [ 63312.2169069 ],
       [ 75187.61618011],
       [126022.83370734],
       [165919.92094638],
       [ 45499.11799708],
       [100605.22494372],
       [ 75187.61618011],
       [ 51436.81763369],
       [ 51436.81763369],
       [ 98938.41472653],
       [ 81125.31581672],
       [142169.12239996],
       [130293.72312675],
       [ 57374.51727029],
       [171857.62058299],
       [ 42530.26817878],
       [171857.62058299],
       [118418.32385354],
       [120085.13407073],
       [164253.11072919],
       [136231.42276336],
       [ 51436.81763369],
       [116751.51363635],
       [116751.51363635],
       [ 81125.31581672],
       [161649.03152697],
       [197275.2293466 ],
       [ 98938.41472653],
       [124356.02349015],
       [ 87063.01545332],
       [ 51436.81763369],
       [ 57374.51727029],
       [165919.92094638],
       [159982.22130978]])

In [25]:
# to know what the orignal prediction was for the testing data
y_test

       Salary
74   120000.0
60   170000.0
89    55000.0
22    50000.0
343  150000.0
..        ...
111   95000.0
307   50000.0
31    55000.0
249  170000.0
102  150000.0

[75 rows x 1 columns]

In [26]:
# to Calculate the Accuracy of the Model
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error,mean_squared_error

In [27]:
# to print the mean absolute error
mean_absolute_error(y_test,y_pred)

9859.883754159075

In [28]:
# to print the mean absolute percentage
per_e = mean_absolute_percentage_error(y_test,y_pred)
per_e

0.10963749345183432

In [29]:
# to print the accuracy in percentage
acc1 = (1-per_e)*100
acc1

89.03625065481657

In [30]:
# Trying other Algorhithms to check which gives the best accuracy

# KNeighbors Regressor

from sklearn.neighbors import KNeighborsRegressor
model2 = KNeighborsRegressor() 
model2.fit(x_train,y_train)
y_pred2 = model2.predict(x_test)
error2 = mean_absolute_percentage_error(y_test,y_pred2)
acc2 = (1-error2)*100
acc2

88.45614776450266

In [31]:
# DecisionTree Regressor

from sklearn.tree import DecisionTreeRegressor
model3 = DecisionTreeRegressor()
model3.fit(x_train,y_train)
y_pred3 = model3.predict(x_test)
error3 = mean_absolute_percentage_error(y_test,y_pred3)
acc3 = (1-error3)*100
acc3

89.18331140155195

In [32]:
# RandomForest Regressor

from sklearn.ensemble import RandomForestRegressor
model4 = RandomForestRegressor()
model4.fit(x_train,y_train)
y_pred4 = model4.predict(x_test)
error4 = mean_absolute_percentage_error(y_test,y_pred4)
acc4 = (1-error4)*100
acc4

C:\Users\hi\Desktop\projects\python_projects\tutorial\tut_tensorflow\.venv\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

89.4344066567915

In [33]:
print("The Acuuracy of Linear Regressor is ",acc1)
print("The Acuuracy of KNeighbors Regressor is ",acc2)
print("The Acuuracy of DecisionTree Regressor is ",acc3)
print("The Acuuracy of RandomForest Regressor is ",acc4)

The Acuuracy of Linear Regressor is  89.03625065481657
The Acuuracy of KNeighbors Regressor is  88.45614776450266
The Acuuracy of DecisionTree Regressor is  89.18331140155195
The Acuuracy of RandomForest Regressor is  89.4344066567915